on:
  pull_request:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v3
        with:
          node-version: 18

      - run: |
          npm ci

      - run: |
          npm run build

      - uses: actions/upload-artifact@v3
        with:
          name: EDCViewer-${{ github.sha }}
          path: build

  # check-style:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v4

  #     - uses: actions/setup-node@v3
  #       with:
  #         node-version: 18

  #     - run: |
  #         npm install clang-format@1.8.0

  #     - run: |
  #         npx clang-format --dry-run --Werror $(find . -name '*.js' -not -path './node_modules/*')

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v3
        with:
          node-version: 18

      - run: |
          npm ci

      - run: |
          npm run test
