on:
  pull_request:
  push:
  workflow_dispatch:

jobs:
  check-style:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - run: |
          sudo apt-get install -y clang-format

      - run: |
          clang-format --dry-run --Werror $(find . -name '*.js')
